version: "3.9"

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 mysite.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True