# Generated by Django 3.2.25 on 2025-03-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('engine', models.CharField(max_length=50, verbose_name='Двигатель')),
                ('horsepower', models.IntegerField(verbose_name='Мощность (л.с.)')),
                ('image_url', models.URLField(verbose_name='URL изображения')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
